# Generated by Django 6.0.5 on 2026-05-12 16:33

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.ImageField(blank=True, help_text='Upload your signature as a transparent PNG', null=True, upload_to='signatures/', validators=[django.core.validators.FileExtensionValidator(['png'])])),
                ('stamp', models.ImageField(blank=True, help_text='Upload your stamp/logo as a transparent PNG', null=True, upload_to='stamps/', validators=[django.core.validators.FileExtensionValidator(['png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
