# Generated by Django 6.0.5 on 2026-05-16 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Phone number for receiving OTP via SMS (e.g. +255712345678)', max_length=20, null=True, unique=True),
        ),
    ]
