# Generated by Django 6.0.5 on 2026-10-07 07:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_make_email_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('signature', models.ImageField(blank=True, help_text='Upload the company signature as a transparent PNG', null=True, upload_to='signatures/', validators=[django.core.validators.FileExtensionValidator(['png'])])),
                ('stamp', models.ImageField(blank=True, help_text='Upload the company stamp/logo as a transparent PNG', null=True, upload_to='stamps/', validators=[django.core.validators.FileExtensionValidator(['png'])])),
                ('is_default', models.BooleanField(default=False, help_text='The company that is selected automatically after login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
    ]
