# Generated by Django 6.0.5 on 2026-05-12 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='signature_x',
        ),
        migrations.RemoveField(
            model_name='document',
            name='signature_y',
        ),
        migrations.RemoveField(
            model_name='document',
            name='stamp_x',
        ),
        migrations.RemoveField(
            model_name='document',
            name='stamp_y',
        ),
        migrations.AddField(
            model_name='document',
            name='total_pages',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement_type', models.CharField(choices=[('signature', 'Signature'), ('stamp', 'Stamp')], max_length=10)),
                ('page_number', models.IntegerField(default=1)),
                ('x', models.FloatField(default=0)),
                ('y', models.FloatField(default=0)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='documents.document')),
            ],
            options={
                'ordering': ['page_number', 'placement_type'],
            },
        ),
    ]
