# Generated by Django 6.0.5 on 2026-05-15 15:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_signature_x_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
