# Generated by Django 6.0.5 on 2026-05-15 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_otp_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='retention_days',
            field=models.IntegerField(default=30, help_text='Number of days to keep this document before automatic deletion'),
        ),
    ]
