# Generated by Django 6.0.5 on 2026-05-15 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_retention_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='retention_days',
            field=models.IntegerField(default=5, help_text='Number of days to keep this document before automatic deletion (0 = keep indefinitely)'),
        ),
    ]
