# Generated by Django 6.0.5 on 2026-05-16 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_retention_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='public_access_token',
            field=models.CharField(blank=True, help_text='Secret token for public (no-login) access to download the signed document', max_length=64, null=True, unique=True),
        ),
    ]
