# Generated by Django 6.0.5 on 2026-10-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_company'),
        ('documents', '0008_add_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='company',
            field=models.ForeignKey(blank=True, help_text="The company this document belongs to (uses that company's signature/stamp)", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='accounts.company'),
        ),
    ]
